name: trusted_time_android
description: "Reliable and accurate time source based on TrustedTime API"
version: 0.0.1
repository: https://gitlab.com/dart-and-flutter-packages/trusted_time_android

topics:
  - time
  - android
  - trustedtime
  - google
  - play-services

environment:
  sdk: ">=3.7.0"
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.peteraleksanderbizjak.trusted_time_android
        pluginClass: TrustedTimeAndroidPlugin