name: trusted_time_android
description: "A Flutter plugin providing reliable and accurate time keeping for Android apps using Google's TrustedTime API."
version: 0.0.3
repository: https://github.com/sunderee/trusted-time-android

topics:
  - time
  - android
  - trustedtime
  - google
  - play-services

environment:
  sdk: ">=3.7.2 <4.0.0"
  flutter: ">=3.29.2"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.peteraleksanderbizjak.trusted_time_android
        pluginClass: TrustedTimeAndroidPlugin